version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=achit
      - POSTGRES_PASSWORD=achit
      - POSTGRES_DB=settings-application
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local